docs: :memo: clarify async components for Vue Router
vuejs/docs-next pull request #1014
Opened 2021-04-24 21:05 UTC by TheDutchCoder

## Description of Problem
The docs around async components can be a bit confusing when people use Vue Router, hopefully this change clarifies the use of async component with Vue Router a bit.

## Proposed Solution
- Change the example of `NextPage.vue` to a more generic `CartFlyout.vue`
- Add a note about async components and Vue Router, with a link to the relevant section in the Router docs.

## Additional Information
N/A

2021-04-26 03:15 UTC, skirtles-code requested changes
Thanks for the PR!

We don't usually reference Vue Router in the main Vue docs but I agree that this is potentially confusing and warrants a mention.

Coming from Vue 2, I thought that async components and lazy loaded routes were effectively the same thing. I imagine a lot of people thought the same. My first reaction when I read this page was that it would be a hassle to upgrade my router config. Hopefully the extra note can help others falling into the same trap.

2021-04-26 13:36 UTC, TheDutchCoder commented on src/guide/migration/async-components.md
> +When using the official Vue Router and you want to asynchronously load (lazy load) router components, you should not use `defineAsyncComponent`. You can read more about this in the (Lazy Loading Rout
Excellent, that's much better (whoops about the brackets lol, didn't even pick that one up!)

2021-04-26 13:36 UTC, TheDutchCoder commented on src/guide/migration/async-components.md
> +const asyncPage = () => import('./CartFlyout.vue')
You're totally right, let me update that!

2021-04-26 13:39 UTC, TheDutchCoder commented
@skirtles-code I've updated the examples and also renamed `CartFlyout.vue` to a more illustrative `Modal.vue`, which I think is more familiar to people and makes more contextual sense.

Let me know what you think!

2021-04-26 15:25 UTC, posva approved these changes

2021-04-27 07:23 UTC, skirtles-code approved these changes
Agreed. I prefer `Modal` too.

2021-04-27 07:24 UTC, merged