[WIP] Migration build flags
vuejs/docs-next pull request #1033
Opened 2021-05-04 16:17 UTC by NataliaTepluhina

This MR is a draft for adding Vue 3.1 Migration build flags

2021-05-05 16:08 UTC, NataliaTepluhina commented
@yyx990803 here is the draft for adding compact build flags to the documentation. I've also added a compact build placeholder document with the list of all flags as SSOT for users, we can remove them if it's not necessary

2021-06-04 13:08 UTC, skirtles-code requested changes

2021-06-04 13:20 UTC, yyx990803 commented on src/guide/migration/functional-components.md
> +  <component v-bind:is="`h${$props.level}`" v-bind="$attrs" />
That would be great, yes please.

2021-06-04 13:24 UTC, yyx990803 commented on src/guide/migration/global-api.md
> +### `Vue.extend` Replaced by `defineComponent`
Agreed. `defineComponent` is introduced purely for TypeScript support as its runtime code is pretty much a noop.

It is more accurate to say that `Vue.extend` is removed:

- There's no longer the concept of "constructable sub-classes" in Vue 3
- Component inheritance is discouraged - favor composition via Composition API instead
- If inheritance is absolutely needed, use the `extends` option.

2021-06-07 16:47 UTC, merged