Vueschool links
vuejs/docs-next pull request #311
Opened 2020-07-21 14:26 UTC by rahaug

This PR adds the approved Vue School links that were added to the Vue 2 documentation in [PR 2379](https://github.com/vuejs/vuejs.org/pull/2379). 

I've made no changes to the links, they are identical to the Vue 2 version. [Screenshots of the placements can be seen here](https://imgur.com/a/j6rkptp)

**Lessons**
[Computed Properties](https://vueschool.io/lessons/vuejs-computed-properties)
[Reusable Components with Props](https://vueschool.io/lessons/reusable-components-with-props)
[Conditional Rendering](https://vueschool.io/lessons/vuejs-conditionals)
[List Rendering](https://vueschool.io/lessons/vuejs-loops)
[Communication between Components with Custom Events](https://vueschool.io/lessons/communication-between-components)

2020-09-16 15:57 UTC, bencodezen commented
Hey @rahaug! I know you mentioned in your PR that these are equivalent to the lessons found in the v2 docs. Since these docs are for v3, I'm thinking it may make more sense to wait until the Vue 3 course for Vue School is out? The reason I mention this is that the v2 site is not going anywhere, so all of the current links for Vue School will still be on there.

2020-09-16 15:58 UTC, bencodezen requested changes
Hey @rahaug! I know you mentioned in your PR that these are equivalent to the lessons found in the v2 docs. Since these docs are for v3, I'm thinking it may make more sense to wait until the Vue 3 course for Vue School is out? The reason I mention this is that the v2 site is not going anywhere, so all of the current links for Vue School will still be on there.

2020-09-18 12:20 UTC, rahaug commented
Hi @bencodezen ! 

Since there are no changes to how we work with computed properties, props, conditional rendering, list rendering, and custom events from Vue 2 to Vue 3, I think it's beneficial and complementary to add the links to the Vue 3 docs as well.

Users might land on the v3 docs from a search and miss out on visual learning aids.

What do you think?

2020-11-08 05:39 UTC, devdreamsolution approved these changes

2021-01-05 20:37 UTC, rahaug commented
The PR is updated with links to free video lessons that were added to the Vue 2 docs in [PR 2177](https://github.com/vuejs/vuejs.org/pull/2177).

I've also refactored to use the new `VideoLesson` component.

[Visuals of all links can be seen here](https://imgur.com/a/hfRc4mF)

**Lessons**
[Class Binding](https://vueschool.io/lessons/vuejs-dynamic-classes)
[Component Registration](https://vueschool.io/lessons/global-vs-local-components)
[Event Handling](https://vueschool.io/lessons/vuejs-user-events)
[Intro to Single File Components](https://vueschool.io/lessons/introduction-to-single-file-components)

**Courses**
[Components Fundamentals](https://vueschool.io/courses/vuejs-components-fundamentals)

2021-01-09 03:27 UTC, bencodezen commented
Thanks for this @rahaug. After reviewing all of the videos, we unfortunately cannot merge this PR. While the concepts are similar from Vue 2 to Vue 3, the code examples and syntax in the lessons reflect an old syntax which would be confusing for users new to the ecosystem.

2021-01-09 03:27 UTC, closed without merging