Update custom-directives.md
vuejs/docs-next pull request #558
Opened 2020-09-27 13:42 UTC by DanielPe05

## Description of Problem
Small typo

2020-09-27 14:02 UTC, NataliaTepluhina requested changes

2020-09-27 14:02 UTC, NataliaTepluhina commented on src/guide/migration/custom-directives.md
> +In Vue 3, we're now supporting fragments, which allow us to return more than one DOM node per component. You can imagine how handy that is for something like a component with multiple lists or the ch
I believe we meant multiple `<li>` tags here:

```suggestion
In Vue 3, we're now supporting fragments, which allow us to return more than one DOM node per component. You can imagine how handy that is for something like a component with multiple `<li>` elements or the children elements of a table:
```

2020-09-29 09:37 UTC, skirtles-code approved these changes

2020-09-30 05:55 UTC, NataliaTepluhina approved these changes
Thank you for the fix!

2020-09-30 05:55 UTC, merged