feat(migration): transition-group (close #648)
vuejs/docs-next pull request #649
Opened 2020-10-24 16:49 UTC by LinusBorg

`<transition-group>` no longer renders a root element by default, since Vue 3 now supports fragements.

2020-10-24 20:24 UTC, skirtles-code requested changes
Looks good. A few small suggestions from me.

2020-10-24 20:24 UTC, skirtles-code commented on src/guide/migration/transition-group.md
> +---
This file needs adding to `config.js` so it'll appear in the sidebar.

2020-10-31 16:32 UTC, sdras commented on src/guide/transitions-list.md
> +- By default, it doesn't render a wrapper element, but you can can element to be rendered with the `tag` attribute.
```suggestion
- By default, it doesn't render a wrapper element, but you can specify an element to be rendered with the `tag` attribute.
```

2020-10-31 16:33 UTC, sdras commented on src/guide/migration/transition-group.md
> +`<transition-group>` no longer renders a root element by default, but can still create one with the `tag` prop
```suggestion
`<transition-group>` no longer renders a root element by default, but can still create one with the `tag` prop.
```

2020-10-31 16:33 UTC, sdras commented on src/guide/migration/transition-group.md
> +## 3.0 Syntax
```suggestion
## 3.x Syntax
```

2020-10-31 16:34 UTC, sdras commented on src/guide/migration/transition-group.md
> +- If you already have `tag` prop defined in your Vue 2 code, like in the example above, everything will work as before
```suggestion
- If you already have the `tag` prop defined in your Vue 2 code, like in the example above, everything will work as before
```

2020-10-31 16:34 UTC, sdras commented on src/guide/migration/transition-group.md
> +- If you didn't have one defined _and_ your styling or other behaviors relied in the presence of the `<span>` root element to work properly, simply add `tag="span"` to the `<transition-group>`:
```suggestion
- If you didn't have one defined _and_ your styling or other behaviors relied on the presence of the `<span>` root element to work properly, simply add `tag="span"` to the `<transition-group>`:
```

2020-10-31 16:35 UTC, sdras commented on src/guide/migration/transition-group.md
> +title: Transition Group root Element
```suggestion
title: Transition Group Root Element
```

2020-10-31 16:42 UTC, sdras commented
This is fantastic! Thank you so much @LinusBorg and also @skirtles-code for the wonderful review

2020-10-31 16:43 UTC, sdras approved these changes

2020-10-31 16:52 UTC, merged