SSR guide
vuejs/docs-next pull request #864
Opened 2021-02-18 15:47 UTC by NataliaTepluhina

## Description of Problem

This is the first PR to start with Server side rendering guide. This particular one covers only the most basic SSR - without templating, without any bundler. I plan to extend this section in the follow-up PRs.

2021-02-21 04:03 UTC, skirtles-code requested changes
I've made a few small suggestions inline.

I had two other thoughts:

1. If we're going to merge this as we go then we should probably have a disclaimer at the top of each page warning that the guide is incomplete.
2. I got a little bit confused by the Express example. The example itself is fine but it doesn't include any client-side hydration. There should probably be a note somewhere that we're only dealing with the server part for now and hydration will be covered later.

On a loosely related note, the API Reference for `mount` suggests that it takes a second argument called `isHydrate`. When I tried playing with SSR myself that threw me for a while. As far as I can tell that isn't true, it only takes a single argument and you just use `createSSRApp` in the client code to trigger hydration. Perhaps something to update when the relevant SSR bits are added to the API Reference.

2021-02-22 16:03 UTC, NataliaTepluhina commented on src/guide/ssr/introduction.md
> +This guide will be very in-depth and assumes you are already familiar with Vue.js itself, and have a decent working knowledge of Node.js and webpack. If you prefer a higher-level solution that provid
Commented this section

2021-02-22 16:06 UTC, NataliaTepluhina commented on src/guide/ssr/getting-started.md
> +// server.js
Removed it altogether as it's a bit early to explain about Node code before we dropped an Express name

2021-02-22 16:10 UTC, NataliaTepluhina commented on src/guide/ssr/getting-started.md
> +To run an application, [Express](https://expressjs.com/):
Extended a bit

2021-02-22 16:21 UTC, NataliaTepluhina commented
@skirtles-code I've added a few sentences and a disclaimer to show the guide is incomplete. As for hydration: it seems in the previous guide it was covered in webpack build, do you think we should have it before?

2021-02-24 11:18 UTC, skirtles-code commented
@NataliaTepluhina I'm not sure how to cover hydration without a build. I tried to create the simplest example I could that used client-side hydration but I don't think it would make for a good documentation example:

https://github.com/skirtles-code/vue-3-ssr-example-no-build

In practice I can't imagine anyone wanting to do it that way and the tricks I used to get it to work are more likely to confuse someone rather than clarifying anything.

I think the paragraph you've added to the end of the current page explaining that client-side hydration will be explained later is sufficient to avoid confusion.

2021-02-24 11:21 UTC, skirtles-code approved these changes

2021-02-24 11:22 UTC, merged