Added `propsData` to migration guide
vuejs/docs-next pull request #916
Opened 2021-02-27 15:48 UTC by NataliaTepluhina

## Description of Problem

Currently, we don't reflect in the Migration guide that `propsData` option was removed. This PR aims to fix this

Close https://github.com/vuejs/docs-next/issues/848

2021-02-28 11:12 UTC, skirtles-code requested changes
A few small tweaks from me.

2021-02-28 11:12 UTC, skirtles-code commented on src/guide/migration/props-data.md
> +```
````suggestion
```js
const app = createApp(
  {
    props: ['username'],
    template: '<div>{{ username }}</div>'
  },
  { username: 'Evan' }
)
```
````

The diff looks complicated but all I've done is move the template to the `template` option, same as the Vue 2 example.

2021-03-02 06:25 UTC, NataliaTepluhina commented
@skirtles-code fixes applied! 👍🏻

2021-03-02 14:08 UTC, skirtles-code approved these changes

2021-03-02 14:08 UTC, merged